language: node_js
node_js:
  - "0.10"
  - "0.11"
services:
  - redis-server
matrix:
  allow_failures:
      - node_js: "0.11"
before_script:
  - npm install -g grunt-cli
  - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list
  - apt-get update
  - apt-get install google-chrome-stable
